### PR TITLE
YUM release changes

### PR DESCRIPTION
**Pull request by jpcoenen**
Some minor changes to `.goreleaser` to allow release to yum repository.

### CODE REVIEW

**Comment by mackenbach** [comment]
@jpcoenen @florisvdg what's the priority of this? Should we merge this before doing a next release of the CLI? If so, let's prioritize.

**Comment by florisvdg** [comment]
We can also wait with it until we split up the goreleaser file for CI. That way we're sure it can't break anything.

**Comment by mackenbach** [comment]
> It means the conventional names for rpm's are used. But... it is not strictly necessary. Looking at it again I'm not sure whether it is nice to rename it just for this single packaging format.

I have very little clue as to how much value this has. We're hosting our own YUM repo correct? Then renaming those files into the ones fit for the yum repo when you push to the repo (which is on s3?) sounds fine to me. 

However, making the `.rpm` files match the `.rpm` convention is also pretty good if you ask me. 

Long story short:

**Comment by jpcoenen** [comment]
> I have very little clue as to how much value this has. We're hosting our own YUM repo correct? Then renaming those files into the ones fit for the yum repo when you push to the repo (which is on s3?) sounds fine to me.
> 
> However, making the `.rpm` files match the `.rpm` convention is also pretty good if you ask me.
> 
> Long story short:

YUM does not care. It will only call our `amd64` binary `X86_64` when you try to install it, regardless of the filename (`secrethub-cli X86_64 v1.2.3``)

**Comment by mackenbach** [comment]
If yum don't care, then let's stay consistent with our own stuff right?

**Comment by jpcoenen** [comment]
Changed it to be consistent with the archives:
```
dist/secrethub-v0.30.0-darwin-amd64.tar.gz
dist/secrethub-v0.30.0-linux-386.deb
dist/secrethub-v0.30.0-linux-386.rpm
dist/secrethub-v0.30.0-linux-386.tar.gz
dist/secrethub-v0.30.0-linux-amd64.deb
dist/secrethub-v0.30.0-linux-amd64.rpm
dist/secrethub-v0.30.0-linux-amd64.tar.gz
dist/secrethub-v0.30.0-linux-arm64.deb
dist/secrethub-v0.30.0-linux-arm64.rpm
dist/secrethub-v0.30.0-linux-arm64.tar.gz
dist/secrethub-v0.30.0-linux-armv5.deb
dist/secrethub-v0.30.0-linux-armv5.rpm
dist/secrethub-v0.30.0-linux-armv5.tar.gz
dist/secrethub-v0.30.0-linux-armv6.deb
dist/secrethub-v0.30.0-linux-armv6.rpm
dist/secrethub-v0.30.0-linux-armv6.tar.gz
dist/secrethub-v0.30.0-linux-armv7.deb
dist/secrethub-v0.30.0-linux-armv7.rpm
dist/secrethub-v0.30.0-linux-armv7.tar.gz
dist/secrethub-v0.30.0-windows-386.zip
dist/secrethub-v0.30.0-windows-amd64.zip
```

**Comment by mackenbach** [comment]
Hmm.. I like how it is now, but we've already released a version of the CLI with a different structure. I'm okay(ish) with 'breaking' this once, but we should be careful and update all the docs and links that refer to it too.

**Comment by jpcoenen** [comment]
As far as I know, all links to it are dynamic. So that should not be a problem.

**Pull request merged**
