### PR TITLE
Fix incorrect int to string conversion 

### PR DESCRIPTION
**Pull request by jpcoenen**
This line breaks compilation under go 1.15

### CODE REVIEW

**Review by SimonBarendse — COMMENTED** [review]
@jpcoenen I've fixed one issue (explained in the commit message). If you agree you can merge this.

**Comment by jpcoenen** [comment]
Apparently it was not as straightforward as I thought.

**Comment by SimonBarendse** [comment]
> Previous implementation outputted something like -rw-r--r-- instead of 0644.

Isn't that a feature?

**Review by SimonBarendse — COMMENTED** [review]
> Previous implementation outputted something like -rw-r--r-- instead of 0644.

Isn't that a feature?

**Comment by jpcoenen** [comment]
> Isn't that a feature?

Shouldn't it be the inverse of the `Set()` function?

**Comment by SimonBarendse** [comment]
Hmm, I'm not sure whether that's required.

I'm checking the docs now at https://golang.org/pkg/flag/#Value , but don't see anything mentioned about that.

**Comment by jpcoenen** [comment]
Still, why would we? We use the digit-format everywhere.

**Review by SimonBarendse — APPROVED** [review]
Yes, that's right. Doesn't hurt to have it like this.

**Pull request merged**
